// Real Payment Gateway Service — Razorpay + Direct UPI (Zero-fee)

export interface PaymentOptions {
  amount: number; // INR
  planName: string;
  customerName: string;
  customerEmail: string;
  orderId?: string;
  onSuccess: (paymentId: string, orderId: string, signature: string) => void;
  onError: (error: string) => void;
}

export const paymentService = {
  /**
   * Razorpay Checkout — needs VITE_RAZORPAY_KEY_ID in .env
   * Sign up free: https://razorpay.com → Settings → API Keys
   */
  openRazorpayCheckout: (options: PaymentOptions) => {
    const key = (import.meta as any).env?.VITE_RAZORPAY_KEY_ID as string | undefined;

    if (!key) {
      // No Razorpay key → fall back to direct UPI notification
      options.onError('RAZORPAY_NOT_CONFIGURED');
      return;
    }

    if (!(window as any).Razorpay) {
      options.onError('Razorpay SDK not loaded. Please check your internet connection and refresh.');
      return;
    }

    const rzpOptions = {
      key,
      amount: options.amount * 100,       // Razorpay uses paise (₹199 = 19900 paise)
      order_id: options.orderId,           // From Supabase Edge Function / backend
      currency: 'INR',
      name: 'Kedar AI',
      description: `${options.planName} Subscription`,
      image: 'https://api.dicebear.com/7.x/shapes/svg?seed=kedarai&backgroundColor=6366f1',
      handler: (response: any) => {
        options.onSuccess(
          response.razorpay_payment_id || '',
          response.razorpay_order_id || options.orderId || '',
          response.razorpay_signature || ''
        );
      },
      prefill: {
        name: options.customerName,
        email: options.customerEmail,
      },
      theme: { color: '#6366f1' },
      modal: {
        ondismiss: () => options.onError('Payment was cancelled by user.')
      }
    };

    const rzp = new (window as any).Razorpay(rzpOptions);
    rzp.on('payment.failed', (response: any) => {
      options.onError(response.error?.description || 'Payment failed. Please try again.');
    });
    rzp.open();
  },

  /**
   * Direct UPI Deep-link (no gateway, zero fees, money goes directly to your bank)
   * Works with GPay, PhonePe, Paytm, BHIM, Cred, and all UPI apps.
   */
  generateUPILink: (upiId: string, amount: number, planName: string): string => {
    if (!upiId) return '';
    const pa = encodeURIComponent(upiId.trim());
    const pn = encodeURIComponent('Kedar AI');
    const tn = encodeURIComponent(`KedarAI ${planName}`);
    return `upi://pay?pa=${pa}&pn=${pn}&am=${amount}&cu=INR&tn=${tn}`;
  },

  /**
   * Dynamic QR Code image for UPI (generated by qrserver.com — free & reliable)
   */
  getUPIQRCodeUrl: (upiId: string, amount: number, planName: string): string => {
    if (!upiId) return '';
    const upiUri = paymentService.generateUPILink(upiId, amount, planName);
    return `https://api.qrserver.com/v1/create-qr-code/?size=220x220&margin=8&data=${encodeURIComponent(upiUri)}`;
  },

  isRazorpayConfigured: (): boolean => {
    return Boolean((import.meta as any).env?.VITE_RAZORPAY_KEY_ID);
  }
};
