import React, { useState, useEffect } from 'react';
import { 
  Sparkles, Play, CheckCircle2, Loader2, CircleDot, 
  ArrowRight, Download, Copy, Check, Terminal, FileCode,
  ShieldCheck, Layers, Cpu, RefreshCw, Box, Code2, Rocket,
  Bug, ExternalLink, PlusCircle, BookOpen, CheckSquare, X
} from 'lucide-react';
import { marked } from 'marked';
import Prism from 'prismjs';
import { useApp } from '../../context/AppContext';
import { agentService } from '../../services/agentService';
import { AgentTask, AgentStep, AgentDeliverable } from '../../types';

export const AgentView: React.FC = () => {
  const { profile, memories, settings, addTask, addRoadmap, showToast, setCurrentSection } = useApp();
  const [goal, setGoal] = useState('');
  const [isRunning, setIsRunning] = useState(false);
  const [activeTask, setActiveTask] = useState<AgentTask | null>(null);
  const [activeTab, setActiveTab] = useState<'pipeline' | 'deliverables' | 'report'>('pipeline');
  const [selectedStepIndex, setSelectedStepIndex] = useState<number>(0);
  const [copied, setCopied] = useState(false);
  const [copiedCodeId, setCopiedCodeId] = useState<string | null>(null);

  const sampleGoals = [
    'Build a real-time Portfolio Website with Next.js 15, Tailwind, and Supabase.',
    'Architect an automated AI Customer Support Bot with WhatsApp Webhook & Gemini.',
    'Build a high-throughput Chat Application with WebSockets, Redis caching, and PostgreSQL.',
    'Create an ATS 95+ Resume Optimizer CLI tool in Python with Google Gemini API.'
  ];

  useEffect(() => {
    Prism.highlightAll();
  }, [activeTask, activeTab, selectedStepIndex]);

  const handleStartAgent = async (customGoal?: string) => {
    const targetGoal = customGoal || goal;
    if (!targetGoal.trim() || isRunning) return;

    setIsRunning(true);
    showToast('Multi-Step Agent Planner analyzing goal...', 'info');

    try {
      // Phase 1: Planning
      const initialTask = await agentService.generateAgentPlan(targetGoal, { profile, memories, settings });
      initialTask.status = 'running';
      setActiveTask(initialTask);
      setActiveTab('pipeline');

      const deliverables: AgentDeliverable[] = [];
      const updatedSteps: AgentStep[] = [...initialTask.steps];

      // Phase 2: Sequential Step Execution
      for (let i = 0; i < updatedSteps.length; i++) {
        setSelectedStepIndex(i);
        updatedSteps[i].status = 'in_progress';
        setActiveTask({ ...initialTask, steps: [...updatedSteps] });

        try {
          const { output, codeSnippet, deliverable } = await agentService.executeStep(
            initialTask,
            updatedSteps[i],
            { profile, memories, settings }
          );

          updatedSteps[i].status = 'completed';
          updatedSteps[i].output = output;
          if (codeSnippet) {
            updatedSteps[i].codeSnippet = codeSnippet;
          }
          if (deliverable) {
            deliverables.push(deliverable);
          }
        } catch (stepErr: any) {
          updatedSteps[i].status = 'failed';
          updatedSteps[i].output = `Execution failed: ${stepErr.message || 'Error executing step'}`;
        }

        setActiveTask({
          ...initialTask,
          steps: [...updatedSteps],
          deliverables: [...deliverables]
        });
      }

      // Phase 3: Final Report
      const finalReport = agentService.generateFinalReport(
        { ...initialTask, steps: updatedSteps },
        deliverables,
        profile.name
      );

      const hasFailed = updatedSteps.some(s => s.status === 'failed');

      const completedTask: AgentTask = {
        ...initialTask,
        steps: updatedSteps,
        deliverables,
        status: hasFailed ? 'failed' : 'completed',
        finalResult: finalReport
      };

      setActiveTask(completedTask);
      showToast(hasFailed ? 'Agent finished with step warnings.' : 'All autonomous agent phases executed successfully!', hasFailed ? 'info' : 'success');
    } catch (err: any) {
      showToast(`Agent planning error: ${err.message || 'Planning failed'}`, 'error');
    } finally {
      setIsRunning(false);
    }
  };

  const handleSaveStepsToTasks = async () => {
    if (!activeTask || activeTask.steps.length === 0) return;
    
    for (const step of activeTask.steps) {
      await addTask({
        title: `[Agent] ${step.title}`,
        description: step.description,
        priority: 'high',
        category: 'project',
        deadline: new Date(Date.now() + 3 * 86400000).toISOString().split('T')[0],
        isCompleted: step.status === 'completed'
      });
    }

    showToast(`Saved ${activeTask.steps.length} steps to Task Planner!`, 'success');
    setCurrentSection('tasks');
  };

  const handleSavePlanToRoadmaps = async () => {
    if (!activeTask) return;

    await addRoadmap({
      id: `road-agent-${Date.now()}`,
      title: `${activeTask.goal.slice(0, 40)} Roadmap`,
      description: `Actionable milestone roadmap generated by Kedar AI Autonomous Swarm.`,
      icon: 'Rocket',
      estimatedWeeks: 4,
      level: 'Intermediate',
      modules: [
        {
          id: 'mod-1',
          title: 'Autonomous Execution Steps',
          topics: activeTask.steps.map(s => s.title),
          completed: false
        }
      ],
      progress: 0
    });

    showToast('Saved Agent Plan to Learning Roadmaps!', 'success');
    setCurrentSection('learning');
  };

  const downloadDeliverable = (deliv: AgentDeliverable) => {
    const blob = new Blob([deliv.content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = deliv.filename || 'deliverable.txt';
    a.click();
    showToast(`Downloaded ${deliv.filename}!`, 'success');
  };

  const copyDeliverableCode = (id: string, code: string) => {
    navigator.clipboard.writeText(code);
    setCopiedCodeId(id);
    showToast('Code copied to clipboard!', 'success');
    setTimeout(() => setCopiedCodeId(null), 2000);
  };

  return (
    <div className="p-4 lg:p-8 max-w-6xl mx-auto space-y-8 animate-fadeIn">
      
      {/* Top Banner */}
      <div className="p-6 rounded-3xl bg-gradient-to-r from-purple-950/70 via-slate-900/90 to-indigo-950/70 border border-purple-500/20 shadow-xl flex flex-col md:flex-row md:items-center justify-between gap-6">
        <div className="space-y-2">
          <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-purple-500/20 text-purple-300 text-xs font-semibold border border-purple-500/30">
            <Sparkles className="w-3.5 h-3.5" />
            <span>Autonomous Multi-Step AI Agent</span>
          </div>
          <h2 className="text-2xl lg:text-3xl font-display font-bold text-white">Agent Mode</h2>
          <p className="text-slate-300 text-sm max-w-xl">
            Input any software or academic goal. The Supervisor Agent decomposes it into structured architectural steps, generates production code and test suites, and enables 1-click database sync.
          </p>
        </div>

        {activeTask && activeTask.status === 'completed' && (
          <div className="flex flex-wrap items-center gap-2">
            <button
              onClick={handleSaveStepsToTasks}
              className="flex items-center gap-1.5 px-3.5 py-2 rounded-xl text-xs font-semibold text-amber-300 bg-amber-500/10 hover:bg-amber-500/20 border border-amber-500/30 transition-all active:scale-95"
            >
              <CheckSquare className="w-3.5 h-3.5" />
              <span>Save to Tasks</span>
            </button>

            <button
              onClick={handleSavePlanToRoadmaps}
              className="flex items-center gap-1.5 px-3.5 py-2 rounded-xl text-xs font-semibold text-emerald-300 bg-emerald-500/10 hover:bg-emerald-500/20 border border-emerald-500/30 transition-all active:scale-95"
            >
              <BookOpen className="w-3.5 h-3.5" />
              <span>Save to Roadmaps</span>
            </button>
          </div>
        )}
      </div>

      {/* Goal Input Section */}
      <div className="p-6 rounded-2xl bg-slate-900/80 border border-slate-800 space-y-4 shadow-lg">
        <label className="text-xs font-semibold text-slate-300 flex items-center gap-1.5">
          <Cpu className="w-4 h-4 text-purple-400" />
          <span>Describe your target objective or software system:</span>
        </label>

        <div className="flex gap-2">
          <input
            type="text"
            placeholder="e.g. Build an AI-powered Exam Practice Platform with Supabase RLS and Gemini API..."
            value={goal}
            onChange={(e) => setGoal(e.target.value)}
            onKeyDown={(e) => e.key === 'Enter' && handleStartAgent()}
            className="flex-1 px-4 py-3 rounded-xl bg-slate-950 border border-slate-800 text-xs text-white outline-none focus:border-purple-500"
          />
          <button
            onClick={() => handleStartAgent()}
            disabled={isRunning || !goal.trim()}
            className="px-6 py-3 rounded-xl bg-gradient-to-r from-purple-600 to-indigo-600 hover:from-purple-500 hover:to-indigo-500 disabled:opacity-50 font-semibold text-xs text-white shadow-md shadow-purple-600/20 flex items-center gap-2 transition-all active:scale-95"
          >
            {isRunning ? <Loader2 className="w-4 h-4 animate-spin" /> : <Play className="w-4 h-4" />}
            <span>{isRunning ? 'Planning & Executing...' : 'Execute Agent'}</span>
          </button>
        </div>

        {/* Sample Goal Suggestions */}
        <div className="flex flex-wrap gap-2 pt-1">
          <span className="text-[11px] font-semibold text-slate-400 self-center">Popular Goals:</span>
          {sampleGoals.map((g, idx) => (
            <button
              key={idx}
              onClick={() => {
                setGoal(g);
                handleStartAgent(g);
              }}
              className="px-2.5 py-1 rounded-lg bg-slate-950/80 hover:bg-slate-800 text-[11px] text-slate-300 border border-slate-800 hover:border-purple-500/40 text-left transition-all"
            >
              {g.slice(0, 45)}...
            </button>
          ))}
        </div>
      </div>

      {/* Agent Execution Pipeline & Results */}
      {activeTask && (
        <div className="space-y-6">
          {/* Navigation Tabs */}
          <div className="flex items-center gap-2 border-b border-slate-800 pb-1">
            <button
              onClick={() => setActiveTab('pipeline')}
              className={`flex items-center gap-2 px-4 py-2 rounded-xl font-semibold text-xs transition-all ${
                activeTab === 'pipeline'
                  ? 'bg-purple-600/20 text-purple-300 border border-purple-500/30'
                  : 'text-slate-400 hover:text-slate-200'
              }`}
            >
              <Layers className="w-4 h-4" />
              <span>Step Pipeline ({activeTask.steps.length})</span>
            </button>

            <button
              onClick={() => setActiveTab('deliverables')}
              className={`flex items-center gap-2 px-4 py-2 rounded-xl font-semibold text-xs transition-all ${
                activeTab === 'deliverables'
                  ? 'bg-purple-600/20 text-purple-300 border border-purple-500/30'
                  : 'text-slate-400 hover:text-slate-200'
              }`}
            >
              <Box className="w-4 h-4" />
              <span>Deliverables ({activeTask.deliverables?.length || 0})</span>
            </button>

            <button
              onClick={() => setActiveTab('report')}
              className={`flex items-center gap-2 px-4 py-2 rounded-xl font-semibold text-xs transition-all ${
                activeTab === 'report'
                  ? 'bg-purple-600/20 text-purple-300 border border-purple-500/30'
                  : 'text-slate-400 hover:text-slate-200'
              }`}
            >
              <FileCode className="w-4 h-4" />
              <span>Final Report</span>
            </button>
          </div>

          {/* Pipeline Tab: Step-by-Step Viewer */}
          {activeTab === 'pipeline' && (
            <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
              
              {/* Steps List */}
              <div className="space-y-3">
                <h4 className="text-xs font-bold text-slate-400 uppercase tracking-wider px-1">Planned Actions</h4>
                {activeTask.steps.map((step, idx) => (
                  <div
                    key={step.id}
                    onClick={() => setSelectedStepIndex(idx)}
                    className={`p-4 rounded-2xl border cursor-pointer transition-all space-y-2 ${
                      selectedStepIndex === idx
                        ? 'bg-purple-950/40 border-purple-500/50 shadow-lg'
                        : 'bg-slate-900/60 border-slate-800/80 hover:border-slate-700'
                    }`}
                  >
                    <div className="flex items-center justify-between">
                      <span className="text-[11px] font-bold text-slate-400 uppercase tracking-wider">
                        Step {idx + 1}: {step.agentRole || 'Agent'}
                      </span>
                      <span className={`px-2 py-0.5 rounded text-[10px] font-semibold uppercase ${
                        step.status === 'completed'
                          ? 'bg-emerald-500/20 text-emerald-300 border border-emerald-500/30'
                          : step.status === 'in_progress'
                          ? 'bg-amber-500/20 text-amber-300 border border-amber-500/30 animate-pulse'
                          : step.status === 'failed'
                          ? 'bg-rose-500/20 text-rose-300 border border-rose-500/30'
                          : 'bg-slate-800 text-slate-400'
                      }`}>
                        {step.status === 'in_progress' ? 'Executing' : step.status === 'completed' ? 'Completed' : step.status === 'failed' ? 'Failed' : 'Planned'}
                      </span>
                    </div>
                    <h5 className="text-xs font-bold text-white">{step.title}</h5>
                    <p className="text-[11px] text-slate-400 line-clamp-2">{step.description}</p>
                  </div>
                ))}
              </div>

              {/* Step Output Inspection */}
              <div className="lg:col-span-2 rounded-2xl bg-slate-900/80 border border-slate-800 p-6 space-y-4 shadow-xl">
                {activeTask.steps[selectedStepIndex] && (
                  <div className="space-y-4">
                    <div className="flex items-center justify-between border-b border-slate-800 pb-3">
                      <div>
                        <span className="text-[11px] text-purple-400 font-bold uppercase tracking-wider">
                          Phase {selectedStepIndex + 1}
                        </span>
                        <h4 className="text-lg font-bold font-display text-white">
                          {activeTask.steps[selectedStepIndex].title}
                        </h4>
                      </div>
                      <span className={`px-2.5 py-1 rounded-full text-xs font-semibold uppercase ${
                        activeTask.steps[selectedStepIndex].status === 'completed'
                          ? 'bg-emerald-500/20 text-emerald-300 border border-emerald-500/30'
                          : activeTask.steps[selectedStepIndex].status === 'in_progress'
                          ? 'bg-amber-500/20 text-amber-300 animate-pulse'
                          : 'bg-slate-800 text-slate-400'
                      }`}>
                        {activeTask.steps[selectedStepIndex].status}
                      </span>
                    </div>

                    <div className="prose prose-invert prose-sm max-w-none text-slate-200 leading-relaxed overflow-x-auto">
                      {activeTask.steps[selectedStepIndex].output ? (
                        <div dangerouslySetInnerHTML={{ __html: marked.parse(activeTask.steps[selectedStepIndex].output || '') as string }} />
                      ) : (
                        <p className="text-slate-400 text-xs italic">Step is planned and waiting for execution...</p>
                      )}
                    </div>
                  </div>
                )}
              </div>

            </div>
          )}

          {/* Deliverables Tab */}
          {activeTab === 'deliverables' && (
            <div className="space-y-4">
              {activeTask.deliverables && activeTask.deliverables.length > 0 ? (
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  {activeTask.deliverables.map(deliv => (
                    <div key={deliv.id} className="p-5 rounded-2xl bg-slate-900/80 border border-slate-800 space-y-3 shadow-lg">
                      <div className="flex items-center justify-between">
                        <div className="flex items-center gap-2">
                          <FileCode className="w-4 h-4 text-purple-400" />
                          <span className="text-xs font-bold text-white">{deliv.filename}</span>
                        </div>
                        <span className="px-2 py-0.5 rounded text-[10px] bg-slate-800 text-slate-300 uppercase">
                          {deliv.language}
                        </span>
                      </div>
                      <p className="text-xs text-slate-400">{deliv.title}</p>

                      <div className="flex items-center justify-end gap-2 pt-2 border-t border-slate-800/80">
                        <button
                          onClick={() => copyDeliverableCode(deliv.id, deliv.content)}
                          className="px-3 py-1.5 rounded-lg bg-slate-800 hover:bg-slate-700 text-slate-300 text-xs flex items-center gap-1"
                        >
                          {copiedCodeId === deliv.id ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
                          <span>Copy</span>
                        </button>
                        <button
                          onClick={() => downloadDeliverable(deliv)}
                          className="px-3 py-1.5 rounded-lg bg-purple-600/20 hover:bg-purple-600/30 text-purple-300 text-xs font-semibold flex items-center gap-1 border border-purple-500/30"
                        >
                          <Download className="w-3.5 h-3.5" />
                          <span>Download</span>
                        </button>
                      </div>
                    </div>
                  ))}
                </div>
              ) : (
                <div className="p-12 text-center rounded-2xl bg-slate-900/40 border border-slate-800 text-slate-400">
                  <p className="text-sm">Execute the agent to generate deliverables.</p>
                </div>
              )}
            </div>
          )}

          {/* Report Tab */}
          {activeTab === 'report' && activeTask.finalResult && (
            <div className="p-6 lg:p-8 rounded-3xl bg-slate-900/80 border border-slate-800 space-y-6 shadow-2xl backdrop-blur-xl">
              <div 
                className="prose prose-invert prose-sm max-w-none text-slate-200"
                dangerouslySetInnerHTML={{ __html: marked.parse(activeTask.finalResult) as string }}
              />
            </div>
          )}
        </div>
      )}

    </div>
  );
};
